// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ground_top_and_bottom.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "ground_top_and_bottom.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace doppia_protobuf {

namespace {

const ::google::protobuf::Descriptor* TopAndBottom_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  TopAndBottom_reflection_ = NULL;
const ::google::protobuf::Descriptor* GroundTopAndBottom_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  GroundTopAndBottom_reflection_ = NULL;

}  // namespace


void protobuf_AssignDesc_ground_5ftop_5fand_5fbottom_2eproto() {
  protobuf_AddDesc_ground_5ftop_5fand_5fbottom_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "ground_top_and_bottom.proto");
  GOOGLE_CHECK(file != NULL);
  TopAndBottom_descriptor_ = file->message_type(0);
  static const int TopAndBottom_offsets_[2] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(TopAndBottom, top_y_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(TopAndBottom, bottom_y_),
  };
  TopAndBottom_reflection_ =
    ::google::protobuf::internal::GeneratedMessageReflection::NewGeneratedMessageReflection(
      TopAndBottom_descriptor_,
      TopAndBottom::default_instance_,
      TopAndBottom_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(TopAndBottom, _has_bits_[0]),
      -1,
      -1,
      sizeof(TopAndBottom),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(TopAndBottom, _internal_metadata_),
      -1);
  GroundTopAndBottom_descriptor_ = file->message_type(1);
  static const int GroundTopAndBottom_offsets_[1] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(GroundTopAndBottom, top_and_bottom_),
  };
  GroundTopAndBottom_reflection_ =
    ::google::protobuf::internal::GeneratedMessageReflection::NewGeneratedMessageReflection(
      GroundTopAndBottom_descriptor_,
      GroundTopAndBottom::default_instance_,
      GroundTopAndBottom_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(GroundTopAndBottom, _has_bits_[0]),
      -1,
      -1,
      sizeof(GroundTopAndBottom),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(GroundTopAndBottom, _internal_metadata_),
      -1);
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_ground_5ftop_5fand_5fbottom_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
      TopAndBottom_descriptor_, &TopAndBottom::default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
      GroundTopAndBottom_descriptor_, &GroundTopAndBottom::default_instance());
}

}  // namespace

void protobuf_ShutdownFile_ground_5ftop_5fand_5fbottom_2eproto() {
  delete TopAndBottom::default_instance_;
  delete TopAndBottom_reflection_;
  delete GroundTopAndBottom::default_instance_;
  delete GroundTopAndBottom_reflection_;
}

void protobuf_AddDesc_ground_5ftop_5fand_5fbottom_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\033ground_top_and_bottom.proto\022\017doppia_pr"
    "otobuf\"/\n\014TopAndBottom\022\r\n\005top_y\030\001 \002(\r\022\020\n"
    "\010bottom_y\030\002 \002(\r\"K\n\022GroundTopAndBottom\0225\n"
    "\016top_and_bottom\030\001 \003(\0132\035.doppia_protobuf."
    "TopAndBottom", 172);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "ground_top_and_bottom.proto", &protobuf_RegisterTypes);
  TopAndBottom::default_instance_ = new TopAndBottom();
  GroundTopAndBottom::default_instance_ = new GroundTopAndBottom();
  TopAndBottom::default_instance_->InitAsDefaultInstance();
  GroundTopAndBottom::default_instance_->InitAsDefaultInstance();
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_ground_5ftop_5fand_5fbottom_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_ground_5ftop_5fand_5fbottom_2eproto {
  StaticDescriptorInitializer_ground_5ftop_5fand_5fbottom_2eproto() {
    protobuf_AddDesc_ground_5ftop_5fand_5fbottom_2eproto();
  }
} static_descriptor_initializer_ground_5ftop_5fand_5fbottom_2eproto_;

namespace {

static void MergeFromFail(int line) GOOGLE_ATTRIBUTE_COLD;
static void MergeFromFail(int line) {
  GOOGLE_CHECK(false) << __FILE__ << ":" << line;
}

}  // namespace


// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int TopAndBottom::kTopYFieldNumber;
const int TopAndBottom::kBottomYFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

TopAndBottom::TopAndBottom()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:doppia_protobuf.TopAndBottom)
}

void TopAndBottom::InitAsDefaultInstance() {
}

TopAndBottom::TopAndBottom(const TopAndBottom& from)
  : ::google::protobuf::Message(),
    _internal_metadata_(NULL) {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:doppia_protobuf.TopAndBottom)
}

void TopAndBottom::SharedCtor() {
  _cached_size_ = 0;
  top_y_ = 0u;
  bottom_y_ = 0u;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

TopAndBottom::~TopAndBottom() {
  // @@protoc_insertion_point(destructor:doppia_protobuf.TopAndBottom)
  SharedDtor();
}

void TopAndBottom::SharedDtor() {
  if (this != default_instance_) {
  }
}

void TopAndBottom::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* TopAndBottom::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return TopAndBottom_descriptor_;
}

const TopAndBottom& TopAndBottom::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_ground_5ftop_5fand_5fbottom_2eproto();
  return *default_instance_;
}

TopAndBottom* TopAndBottom::default_instance_ = NULL;

TopAndBottom* TopAndBottom::New(::google::protobuf::Arena* arena) const {
  TopAndBottom* n = new TopAndBottom;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void TopAndBottom::Clear() {
#define ZR_HELPER_(f) reinterpret_cast<char*>(\
  &reinterpret_cast<TopAndBottom*>(16)->f)

#define ZR_(first, last) do {\
  ::memset(&first, 0,\
           ZR_HELPER_(last) - ZR_HELPER_(first) + sizeof(last));\
} while (0)

  ZR_(top_y_, bottom_y_);

#undef ZR_HELPER_
#undef ZR_

  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  if (_internal_metadata_.have_unknown_fields()) {
    mutable_unknown_fields()->Clear();
  }
}

bool TopAndBottom::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:doppia_protobuf.TopAndBottom)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // required uint32 top_y = 1;
      case 1: {
        if (tag == 8) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &top_y_)));
          set_has_top_y();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(16)) goto parse_bottom_y;
        break;
      }

      // required uint32 bottom_y = 2;
      case 2: {
        if (tag == 16) {
         parse_bottom_y:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &bottom_y_)));
          set_has_bottom_y();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:doppia_protobuf.TopAndBottom)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:doppia_protobuf.TopAndBottom)
  return false;
#undef DO_
}

void TopAndBottom::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:doppia_protobuf.TopAndBottom)
  // required uint32 top_y = 1;
  if (has_top_y()) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(1, this->top_y(), output);
  }

  // required uint32 bottom_y = 2;
  if (has_bottom_y()) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(2, this->bottom_y(), output);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:doppia_protobuf.TopAndBottom)
}

::google::protobuf::uint8* TopAndBottom::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:doppia_protobuf.TopAndBottom)
  // required uint32 top_y = 1;
  if (has_top_y()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt32ToArray(1, this->top_y(), target);
  }

  // required uint32 bottom_y = 2;
  if (has_bottom_y()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt32ToArray(2, this->bottom_y(), target);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:doppia_protobuf.TopAndBottom)
  return target;
}

int TopAndBottom::RequiredFieldsByteSizeFallback() const {
  int total_size = 0;

  if (has_top_y()) {
    // required uint32 top_y = 1;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::UInt32Size(
        this->top_y());
  }

  if (has_bottom_y()) {
    // required uint32 bottom_y = 2;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::UInt32Size(
        this->bottom_y());
  }

  return total_size;
}
int TopAndBottom::ByteSize() const {
  int total_size = 0;

  if (((_has_bits_[0] & 0x00000003) ^ 0x00000003) == 0) {  // All required fields are present.
    // required uint32 top_y = 1;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::UInt32Size(
        this->top_y());

    // required uint32 bottom_y = 2;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::UInt32Size(
        this->bottom_y());

  } else {
    total_size += RequiredFieldsByteSizeFallback();
  }
  if (_internal_metadata_.have_unknown_fields()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void TopAndBottom::MergeFrom(const ::google::protobuf::Message& from) {
  if (GOOGLE_PREDICT_FALSE(&from == this)) MergeFromFail(__LINE__);
  const TopAndBottom* source = 
      ::google::protobuf::internal::DynamicCastToGenerated<const TopAndBottom>(
          &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void TopAndBottom::MergeFrom(const TopAndBottom& from) {
  if (GOOGLE_PREDICT_FALSE(&from == this)) MergeFromFail(__LINE__);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_top_y()) {
      set_top_y(from.top_y());
    }
    if (from.has_bottom_y()) {
      set_bottom_y(from.bottom_y());
    }
  }
  if (from._internal_metadata_.have_unknown_fields()) {
    mutable_unknown_fields()->MergeFrom(from.unknown_fields());
  }
}

void TopAndBottom::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void TopAndBottom::CopyFrom(const TopAndBottom& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool TopAndBottom::IsInitialized() const {
  if ((_has_bits_[0] & 0x00000003) != 0x00000003) return false;

  return true;
}

void TopAndBottom::Swap(TopAndBottom* other) {
  if (other == this) return;
  InternalSwap(other);
}
void TopAndBottom::InternalSwap(TopAndBottom* other) {
  std::swap(top_y_, other->top_y_);
  std::swap(bottom_y_, other->bottom_y_);
  std::swap(_has_bits_[0], other->_has_bits_[0]);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  std::swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata TopAndBottom::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = TopAndBottom_descriptor_;
  metadata.reflection = TopAndBottom_reflection_;
  return metadata;
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// TopAndBottom

// required uint32 top_y = 1;
bool TopAndBottom::has_top_y() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
void TopAndBottom::set_has_top_y() {
  _has_bits_[0] |= 0x00000001u;
}
void TopAndBottom::clear_has_top_y() {
  _has_bits_[0] &= ~0x00000001u;
}
void TopAndBottom::clear_top_y() {
  top_y_ = 0u;
  clear_has_top_y();
}
 ::google::protobuf::uint32 TopAndBottom::top_y() const {
  // @@protoc_insertion_point(field_get:doppia_protobuf.TopAndBottom.top_y)
  return top_y_;
}
 void TopAndBottom::set_top_y(::google::protobuf::uint32 value) {
  set_has_top_y();
  top_y_ = value;
  // @@protoc_insertion_point(field_set:doppia_protobuf.TopAndBottom.top_y)
}

// required uint32 bottom_y = 2;
bool TopAndBottom::has_bottom_y() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
void TopAndBottom::set_has_bottom_y() {
  _has_bits_[0] |= 0x00000002u;
}
void TopAndBottom::clear_has_bottom_y() {
  _has_bits_[0] &= ~0x00000002u;
}
void TopAndBottom::clear_bottom_y() {
  bottom_y_ = 0u;
  clear_has_bottom_y();
}
 ::google::protobuf::uint32 TopAndBottom::bottom_y() const {
  // @@protoc_insertion_point(field_get:doppia_protobuf.TopAndBottom.bottom_y)
  return bottom_y_;
}
 void TopAndBottom::set_bottom_y(::google::protobuf::uint32 value) {
  set_has_bottom_y();
  bottom_y_ = value;
  // @@protoc_insertion_point(field_set:doppia_protobuf.TopAndBottom.bottom_y)
}

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int GroundTopAndBottom::kTopAndBottomFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

GroundTopAndBottom::GroundTopAndBottom()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:doppia_protobuf.GroundTopAndBottom)
}

void GroundTopAndBottom::InitAsDefaultInstance() {
}

GroundTopAndBottom::GroundTopAndBottom(const GroundTopAndBottom& from)
  : ::google::protobuf::Message(),
    _internal_metadata_(NULL) {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:doppia_protobuf.GroundTopAndBottom)
}

void GroundTopAndBottom::SharedCtor() {
  _cached_size_ = 0;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

GroundTopAndBottom::~GroundTopAndBottom() {
  // @@protoc_insertion_point(destructor:doppia_protobuf.GroundTopAndBottom)
  SharedDtor();
}

void GroundTopAndBottom::SharedDtor() {
  if (this != default_instance_) {
  }
}

void GroundTopAndBottom::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* GroundTopAndBottom::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return GroundTopAndBottom_descriptor_;
}

const GroundTopAndBottom& GroundTopAndBottom::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_ground_5ftop_5fand_5fbottom_2eproto();
  return *default_instance_;
}

GroundTopAndBottom* GroundTopAndBottom::default_instance_ = NULL;

GroundTopAndBottom* GroundTopAndBottom::New(::google::protobuf::Arena* arena) const {
  GroundTopAndBottom* n = new GroundTopAndBottom;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void GroundTopAndBottom::Clear() {
  top_and_bottom_.Clear();
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  if (_internal_metadata_.have_unknown_fields()) {
    mutable_unknown_fields()->Clear();
  }
}

bool GroundTopAndBottom::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:doppia_protobuf.GroundTopAndBottom)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // repeated .doppia_protobuf.TopAndBottom top_and_bottom = 1;
      case 1: {
        if (tag == 10) {
          DO_(input->IncrementRecursionDepth());
         parse_loop_top_and_bottom:
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtualNoRecursionDepth(
                input, add_top_and_bottom()));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(10)) goto parse_loop_top_and_bottom;
        input->UnsafeDecrementRecursionDepth();
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:doppia_protobuf.GroundTopAndBottom)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:doppia_protobuf.GroundTopAndBottom)
  return false;
#undef DO_
}

void GroundTopAndBottom::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:doppia_protobuf.GroundTopAndBottom)
  // repeated .doppia_protobuf.TopAndBottom top_and_bottom = 1;
  for (unsigned int i = 0, n = this->top_and_bottom_size(); i < n; i++) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      1, this->top_and_bottom(i), output);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:doppia_protobuf.GroundTopAndBottom)
}

::google::protobuf::uint8* GroundTopAndBottom::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:doppia_protobuf.GroundTopAndBottom)
  // repeated .doppia_protobuf.TopAndBottom top_and_bottom = 1;
  for (unsigned int i = 0, n = this->top_and_bottom_size(); i < n; i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteMessageNoVirtualToArray(
        1, this->top_and_bottom(i), target);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:doppia_protobuf.GroundTopAndBottom)
  return target;
}

int GroundTopAndBottom::ByteSize() const {
  int total_size = 0;

  // repeated .doppia_protobuf.TopAndBottom top_and_bottom = 1;
  total_size += 1 * this->top_and_bottom_size();
  for (int i = 0; i < this->top_and_bottom_size(); i++) {
    total_size +=
      ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
        this->top_and_bottom(i));
  }

  if (_internal_metadata_.have_unknown_fields()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void GroundTopAndBottom::MergeFrom(const ::google::protobuf::Message& from) {
  if (GOOGLE_PREDICT_FALSE(&from == this)) MergeFromFail(__LINE__);
  const GroundTopAndBottom* source = 
      ::google::protobuf::internal::DynamicCastToGenerated<const GroundTopAndBottom>(
          &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void GroundTopAndBottom::MergeFrom(const GroundTopAndBottom& from) {
  if (GOOGLE_PREDICT_FALSE(&from == this)) MergeFromFail(__LINE__);
  top_and_bottom_.MergeFrom(from.top_and_bottom_);
  if (from._internal_metadata_.have_unknown_fields()) {
    mutable_unknown_fields()->MergeFrom(from.unknown_fields());
  }
}

void GroundTopAndBottom::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void GroundTopAndBottom::CopyFrom(const GroundTopAndBottom& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool GroundTopAndBottom::IsInitialized() const {

  if (!::google::protobuf::internal::AllAreInitialized(this->top_and_bottom())) return false;
  return true;
}

void GroundTopAndBottom::Swap(GroundTopAndBottom* other) {
  if (other == this) return;
  InternalSwap(other);
}
void GroundTopAndBottom::InternalSwap(GroundTopAndBottom* other) {
  top_and_bottom_.UnsafeArenaSwap(&other->top_and_bottom_);
  std::swap(_has_bits_[0], other->_has_bits_[0]);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  std::swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata GroundTopAndBottom::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = GroundTopAndBottom_descriptor_;
  metadata.reflection = GroundTopAndBottom_reflection_;
  return metadata;
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// GroundTopAndBottom

// repeated .doppia_protobuf.TopAndBottom top_and_bottom = 1;
int GroundTopAndBottom::top_and_bottom_size() const {
  return top_and_bottom_.size();
}
void GroundTopAndBottom::clear_top_and_bottom() {
  top_and_bottom_.Clear();
}
const ::doppia_protobuf::TopAndBottom& GroundTopAndBottom::top_and_bottom(int index) const {
  // @@protoc_insertion_point(field_get:doppia_protobuf.GroundTopAndBottom.top_and_bottom)
  return top_and_bottom_.Get(index);
}
::doppia_protobuf::TopAndBottom* GroundTopAndBottom::mutable_top_and_bottom(int index) {
  // @@protoc_insertion_point(field_mutable:doppia_protobuf.GroundTopAndBottom.top_and_bottom)
  return top_and_bottom_.Mutable(index);
}
::doppia_protobuf::TopAndBottom* GroundTopAndBottom::add_top_and_bottom() {
  // @@protoc_insertion_point(field_add:doppia_protobuf.GroundTopAndBottom.top_and_bottom)
  return top_and_bottom_.Add();
}
::google::protobuf::RepeatedPtrField< ::doppia_protobuf::TopAndBottom >*
GroundTopAndBottom::mutable_top_and_bottom() {
  // @@protoc_insertion_point(field_mutable_list:doppia_protobuf.GroundTopAndBottom.top_and_bottom)
  return &top_and_bottom_;
}
const ::google::protobuf::RepeatedPtrField< ::doppia_protobuf::TopAndBottom >&
GroundTopAndBottom::top_and_bottom() const {
  // @@protoc_insertion_point(field_list:doppia_protobuf.GroundTopAndBottom.top_and_bottom)
  return top_and_bottom_;
}

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// @@protoc_insertion_point(namespace_scope)

}  // namespace doppia_protobuf

// @@protoc_insertion_point(global_scope)
